In [1]:
#Pandas
import pandas as pd

# importing dataframe

In [2]:
iris=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [3]:
df=iris.copy()

In [4]:
# pass argument to see how many rows you want to see

df.shape
df.dtypes
df.head()
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [5]:
df.columns=['sl','sw','pl','pw','flower_type']

In [6]:
df.describe()
df.sl
#OR
df['sl']
df.isnull().sum()

#Access Values using iloc only
df.iloc[1:4,2:4]

    pl   pw
1  1.3  0.2
2  1.5  0.2
3  1.4  0.2

In [7]:
dfcopy=df.drop(0)
# dfcopy=df.drop(1)
dfcopy.drop(3,inplace=True)
dfcopy

      sl   sw   pl   pw     flower_type
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[147 rows x 5 columns]

In [8]:
#Dropping by position and not by label by:
df.drop(df.index[0],inplace=True)
#Remove multiple rows based on position by":
df.drop(df.index[[1,2]],inplace=True)
df.head()

    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa

In [9]:
# Just like the select command in SQL and putting conditons alongwith
c1=df[df.flower_type=='Iris-setosa']

In [10]:
# iloc vs loc
print(df.head())
print()
print(df.iloc[0]) #this is position based
print()
print(df.loc[5]) # and this is label based

    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa

sl                     4.7
sw                     3.2
pl                     1.3
pw                     0.2
flower_type    Iris-setosa
Name: 1, dtype: object

sl                     4.6
sw                     3.4
pl                     1.4
pw                     0.3
flower_type    Iris-setosa
Name: 5, dtype: object

In [11]:
# Adding a row will add it to the end of the datframe
df.loc[149]=[1,2,3,4,"Iris-setosa"]
df.tail()

      sl   sw   pl   pw     flower_type
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
149  1.0  2.0  3.0  4.0     Iris-setosa

In [12]:
df

      sl   sw   pl   pw     flower_type
1    4.7  3.2  1.3  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
149  1.0  2.0  3.0  4.0     Iris-setosa

[147 rows x 5 columns]

In [13]:
df.reset_index(drop=True,inplace=True)
df.index

RangeIndex(start=0, stop=147, step=1)

In [14]:
df["Gender"]="Female"
df.iloc[0:10,5]="Male"
def f(s):
    if s == "Male":
        return 0
    else:
        return 1
df["sex"]=df.Gender.apply(f)
df.drop("sex",axis=1,inplace=True)
del df["Gender"]
df

      sl   sw   pl   pw     flower_type
0    4.7  3.2  1.3  0.2     Iris-setosa
1    5.4  3.9  1.7  0.4     Iris-setosa
2    4.6  3.4  1.4  0.3     Iris-setosa
3    5.0  3.4  1.5  0.2     Iris-setosa
4    4.4  2.9  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
142  6.3  2.5  5.0  1.9  Iris-virginica
143  6.5  3.0  5.2  2.0  Iris-virginica
144  6.2  3.4  5.4  2.3  Iris-virginica
145  5.9  3.0  5.1  1.8  Iris-virginica
146  1.0  2.0  3.0  4.0     Iris-setosa

[147 rows x 5 columns]